config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'site#index'

  namespace :market_data, only: %i[index show] do
    resources :currencies, id: /[[:upper:]]{6}|[[:digit:]]+/
    resources :equities
    resources :options
  end

  resources :equities

  resources :asset_pairs do
    resources :exchange_rates, shallow: true
    resources :options, shallow: true do
      post 'compute', on: :member
    end
  end
  get 'options', to: 'options#index'

  # The Country and Currency models return the 3-letter alphabetic code instead
  # of their internal ID (except for historic currencies) in their #to_param
  # methods. We restrict the routing :id parameter to values that could be
  # internal ID, numeric code or alphabetic code.
  # We also restrict to the actions #index and #show.
  resources :currencies, id: /[[:upper:]]{3}|[[:digit:]]+/, only: %i[index show]
  resources :countries, id: /[[:upper:]]{2,3}|[[:digit:]]+/,
                        only: %i[index show] do
    resources :exchanges, id: /.*/, shallow: true
  end
  get '/exchanges', to: 'exchanges#index'

  # Redirect alphabetic codes that aren't written in, but required to be,
  # entirely uppercase to the uppercase equivalent.
  # Each line in the following Hash is of the format
  # +controller: id_constraints+
  {
    countries: /[[:alpha:]]{2,3}/,
    currencies: /[[:alpha:]]{3}/,
    'market_data/currencies': /[[:alpha:]]{6}/
  }.each do |controller, id|
    get "/#{controller}/:id",
        id:, to: redirect { |p| "/#{controller}/#{p[:id].upcase}" }
  end
end

app/models/exchange.rb
# frozen_string_literal: true

##
# A securities exchange.
class Exchange < ApplicationRecord
  belongs_to :country

  has_many :security_listings, dependent: :delete_all
  has_many :equities, through: :security_listings, source: :security,
                      source_type: 'Equity'

  validates :symbol, format: { without: /:/ }, uniqueness: true, presence: true
  validates :timezone, timezone: true

  class << self
    ##
    # Returns the first result of a case insensitive match between +symbol+ and
    # the #symbol column.
    #
    # Raises an error if not found.
    # TODO: Reconsider method naming so we dont have to disable Rubocop for
    #       calls to it.
    def find_by_symbol_case_insensitive!(symbol)
      symbol_like_id = arel_table[:symbol].matches(sanitize_sql_like(symbol))
      where(symbol_like_id).first!
    end

    ##
    # Like #find_by_symbol_case_insensitive!, but returns +nil+ if not found.
    def find_by_symbol_case_insensitive(symbol)
      find_by!(symbol_case_insensitive: symbol)
    rescue ActiveRecord::RecordNotFound
      nil
    end

    ##
    # Returns the record where the #symbol or the #id column match +id+.
    #
    # If not found, does a case insensitive search of the #symbol column.
    # Raises ActiveRecord::RecordNotFound if not found.
    def smart_find!(id) = where(symbol: id).or(where(id:)).first!

    ##
    # Like #smart_find!, but returns +nil+ if not found.
    def smart_find(id)
      smart_find!(id)
    rescue ActiveRecord::RecordNotFound
      nil
    end
  end

  scope :equities,
        -> { Equity.with_exchange_symbol.where(exchanges: self) }

  def to_param = symbol
end

app/controllers/exchanges_controller.rb
# frozen_string_literal: true

# :nodoc:
class ExchangesController < ApplicationController
  before_action :set_exchange, only: %i[show edit update destroy]
  before_action :set_country, only: %i[index show new create]

  # GET /exchanges or /exchanges.json
  def index
    @exchanges = Exchange.all
  end

  # GET /exchanges/1 or /exchanges/1.json
  def show; end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new(country: @country)
  end

  # GET /exchanges/1/edit
  def edit; end

  # POST /exchanges or /exchanges.json
  def create
    @exchange = Exchange.new(exchange_params)

    respond_to do |format|
      if @exchange.save
        format.html do
          redirect_to exchange_url(@exchange),
                      notice: 'Exchange was successfully created.'
        end
        format.json { render :show, status: :created, location: @exchange }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @exchange.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /exchanges/1 or /exchanges/1.json
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html do
          redirect_to exchange_url(@exchange),
                      notice: 'Exchange was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @exchange.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /exchanges/1 or /exchanges/1.json
  def destroy
    @exchange.destroy

    respond_to do |format|
      format.html do
        redirect_to exchanges_url,
                    notice: 'Exchange was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exchange
    @exchange = Exchange.smart_find!(params[:id])
  rescue ActiveRecord::RecordNotFound
    # rubocop:disable Rails/DynamicFindBy
    exchange = Exchange.find_by_symbol_case_insensitive!(params[:id])
    # rubocop:enable  Rails/DynamicFindBy
    redirect_to request.parameters.merge(id: exchange.symbol)
  end

  def set_country
    @country = @exchange&.country || Country.smart_find(params[:country_id])
  end

  # Only allow a list of trusted parameters through.
  def exchange_params
    params.require(:exchange).permit(:country_id, :symbol, :name, :timezone)
  end
end

app/helpers/exchanges_helper.rb
# frozen_string_literal: true

# :nodoc:
module ExchangesHelper
end

app/views/exchanges/_exchange.html.erb
<%= show exchange, associations: :country,
                   attributes: %i[name symbol timezone],
                   link: :name do |s| %>
  <%= s.content_tag s.attribute_list_tag_name,
                    class: 'model-attributes-list' do |s| %>
    <%= s.attribute %i[name symbol] %>
    <%= s.association :country do |s| %>
      <%= s.name_tag s.name %>
      <%= s.values_tag link_to(s.value.alpha3_code, s.value) %>
    <% end %>
    <%= s.attribute :timezone %>
  <% end %>
<% end %>

app/views/exchanges/_form.html.erb
<%= form_with(model: [@country, exchange]) do |form| %>
  <% if exchange.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
        <% exchange.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <span><%= exchange.t :country_id %></span>
    <span><%= exchange.country.to_human_s %></span>
    <%= form.hidden_field :country_id %>
  </div>

  <div>
    <%= form.label :symbol, style: "display: block" %>
    <%= form.text_field :symbol %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :timezone %>
    <%= form.text_field :timezone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing exchange</h1>

<%= render "form", exchange: @exchange %>

<br>

<div>
  <%= link_to "Show this exchange", @exchange %> |
  <%= link_to "Back to exchanges", exchanges_path %>
</div>

app/views/exchanges/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Exchanges</h1>

<div id="exchanges">
  <% @exchanges.each do |exchange| %>
    <%= render exchange %>
  <% end %>
</div>

<% if @country.present? %>
  <%= link_to "New exchange", new_country_exchange_path(@country) %>
<% end %>

app/views/exchanges/new.html.erb
<h1>New exchange</h1>

<%= render "form", exchange: @exchange %>

<br>

<div>
  <%= link_to "Back to exchanges", country_exchanges_path(@country) %>
</div>

app/views/exchanges/show.html.erb
<% title_tag! @exchange.name %>

<%= show @exchange, associations: %i[country equities] do |s| %>
  <%= s.attribute :name do |s| %>
    <%= s.content_tag :h1, s.value %>
  <% end %>

  <%= s.content_tag_if_name s.attribute_list_tag_name,
                            class: 'model-attributes-list' do |s| %>
    <%= s.attribute :symbol %>
    <%= s.association :country do |s| %>
      <%= s.name_tag s.name %>
      <%= s.values_tag link_to(s.value.alpha3_code, s.value) %>
    <% end %>
    <%= s.attribute :timezone %>
  <% end %>

  <h2 id="security_listings"><%= t '.security_listings',
                                   default: 'Listed Securities' %></h2>
  <%= s.association :equities, name_tag_name: :h3, values_tag_name: :ul,
                    children_tag_name: :li %>
<% end %>