config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'site#index'

  namespace :market_data, only: %i[index show] do
    resources :currencies, id: /[[:upper:]]{6}|[[:digit:]]+/
    resources :equities
    resources :options
  end

  resources :equities

  resources :asset_pairs do
    resources :exchange_rates, shallow: true
    resources :options, shallow: true do
      post 'compute', on: :member
    end
  end
  get 'options', to: 'options#index'

  # The Country and Currency models return the 3-letter alphabetic code instead
  # of their internal ID (except for historic currencies) in their #to_param
  # methods. We restrict the routing :id parameter to values that could be
  # internal ID, numeric code or alphabetic code.
  # We also restrict to the actions #index and #show.
  resources :currencies, id: /[[:upper:]]{3}|[[:digit:]]+/, only: %i[index show]
  resources :countries, id: /[[:upper:]]{2,3}|[[:digit:]]+/,
                        only: %i[index show] do
    resources :exchanges, id: /.*/, shallow: true
  end
  get '/exchanges', to: 'exchanges#index'

  # Redirect alphabetic codes that aren't written in, but required to be,
  # entirely uppercase to the uppercase equivalent.
  # Each line in the following Hash is of the format
  # +controller: id_constraints+
  {
    countries: /[[:alpha:]]{2,3}/,
    currencies: /[[:alpha:]]{3}/,
    'market_data/currencies': /[[:alpha:]]{6}/
  }.each do |controller, id|
    get "/#{controller}/:id",
        id:, to: redirect { |p| "/#{controller}/#{p[:id].upcase}" }
  end
end

app/models/asset_pair.rb
# frozen_string_literal: true

##
# Associates two polymorphic assets into one asset pair. Typically, this would
# be with an Equity, Option (tbd) or Currency as #base_asset, and a(nother)
# Currency as #counter_asset.
# AssetPairs have many #exchange_rates, which represent prices or quotes on the
# AssetPair.
#
# Note: If the relation returned by the associated block groups by the column
# +:asset_pair_id+, this column will be replaced by +'asset_pairs.id'+ to
# preserve the Left Outer Join generated by ::includes.
class AssetPair < ApplicationRecord
  class << self
    ##
    # Returns the default +model_name+ for AssetPair, and a patched one for
    # subclasses.
    #
    # In subclasses, the following changes are done to +model_name+:
    # [i18n_key]
    #             Derived from +subclass::basename+
    # [route_key]
    #             Derived from +subclass::basename+ and namespaced in
    #             +'market_data/'+
    # [singular_route_key]
    #             +route_key+, singularized
    def model_name
      return super if self == AssetPair

      # rubocop:disable Naming/MemoizedInstanceVariableName
      @_model_name ||= AssetPair.model_name.dup.tap do |model_name|
        model_name.i18n_key = basename.underscore.to_sym
        model_name.route_key = ActiveSupport::Inflector.pluralize(
          "market_data_#{model_name.__send__(:_singularize, basename)}", :en
        )
        model_name.singular_route_key =
          ActiveSupport::Inflector.singularize(model_name.route_key)
      end
      # rubocop:enable  Naming/MemoizedInstanceVariableName
    end

    def includes_exchange_rates
      query = includes(:exchange_rates).references(:exchange_rates)
      return query unless block_given?

      other = yield ExchangeRate
      other.group_values.map! do |value|
        value.in?([:asset_pair_id, 'asset_pair_id']) ? 'asset_pairs.id' : value
      end
      query.merge(other)
    end

    def preload_all(&)
      preload(:base_asset, :counter_asset).includes_exchange_rates(&)
    end

    private

    def inherited(subclass)
      super
      subclass.__send__(:default_scope) { of_base_type(subclass.basename) }
    end
  end

  belongs_to :base_asset, polymorphic: true
  belongs_to :counter_asset, polymorphic: true

  has_many :exchange_rates, dependent: :destroy
  has_many :options, inverse_of: :underlying, foreign_key: :underlying_id,
                     dependent: :destroy

  # TODO: The default error message is referring to this attribute, but the
  #       constraint actually prevents creation of duplicate AssetPairs.
  validates :counter_asset_type,
            uniqueness: {
              scope: %i[counter_asset_id base_asset_type base_asset_id]
            }

  # :section: Asset based selectors

  scope :in, ->(counter_asset) { where(counter_asset:) }
  scope :of, ->(base_asset) { where(base_asset:) }
  scope :of_base_type, ->(type) { where(base_asset_type: type.to_s) }

  # :section: ExchangeRate selectors

  scope :exchange_rates, -> { ExchangeRate.where(asset_pair: self) }

  ##
  # Defines a bunch of scopes that filter associated exchange_rates based on
  # their types.
  #
  # Methods are named after their types.
  # :call-seq:
  #     chart_adjusted_rates => ...
  #     chart_others         => ...
  #     chart_rates          => ...
  #     charts               => ...
  #     net_asset_values     => ...
  #     others               => ...
  #     quote_asks           => ...
  #     quote_bids           => ...
  #     quote_mids           => ...
  #     settlement_rates     => ...
  #     trades               => ...
  ExchangeRate.descendants.each do |type|
    scope type.to_s[14..].remove('::').tableize.to_sym,
          -> { exchange_rates.of_type(type) }
  end

  def to_human_s(*args, **opts)
    base_asset = self.base_asset.to_human_s
    counter_asset = self.counter_asset.to_human_s

    super(*args, **opts.merge(base_asset:, counter_asset:,
                              default: "#{base_asset} (#{counter_asset})"))
  end

  def to_param
    return super if instance_of?(AssetPair) || !association(:base_asset).loaded?

    _to_param
  end

  private

  def _to_param = base_asset.to_param
end

app/models/asset_pair/currency.rb
# frozen_string_literal: true

##
# Class enabling the rendering of AssetPairs in a dedicated
# forex controller while maintaining the ability to manage
# AssetPairs regardless of type in the AssetPairsController.
class AssetPair::Currency < AssetPair
  private

  def _to_param
    return id.to_i unless association(:counter_asset).loaded?

    "#{base_asset.to_param}#{counter_asset.to_param}"
  end
end

app/models/asset_pair/equity.rb
# frozen_string_literal: true

##
# Class enabling the rendering of AssetPairs in a dedicated
# equity controller while maintaining the ability to manage
# AssetPairs regardless of type in the AssetPairsController.
class AssetPair::Equity < AssetPair
  class << self
    def preload_all(...) = super.preload(base_asset: :exchange)
  end
end

app/models/asset_pair/option.rb
# frozen_string_literal: true

##
# Class enabling the rendering of AssetPairs in a dedicated
# options controller while maintaining the ability to manage
# AssetPairs regardless of type in the AssetPairsController.
class AssetPair::Option < AssetPair; end

app/controllers/asset_pairs_controller.rb
# frozen_string_literal: true

# :nodoc:
class AssetPairsController < ApplicationController
  class << self
    ##
    # Returns a relation selecting all AssetPairs. In subclasses, returns a
    # relation selecting all AssetPairs where +base_asset_type+ is
    # +subclass::model_name+.
    def asset_pairs
      return AssetPair.all if self == AssetPairsController

      "AssetPair::#{model_name}".constantize.all
    end
  end

  delegate :asset_pairs, to: :class

  before_action :set_asset_pair, only: %i[show edit update destroy]

  # GET /asset_pairs or /asset_pairs.json
  def index
    @asset_pairs = asset_pairs.preload_all(&:latest_or_none)
  end

  # GET /asset_pairs/1 or /asset_pairs/1.json
  def show; end

  # GET /asset_pairs/new
  def new
    @asset_pair = AssetPair.new
  end

  # GET /asset_pairs/1/edit
  def edit; end

  # POST /asset_pairs or /asset_pairs.json
  def create
    @asset_pair = AssetPair.new(asset_pair_params)

    respond_to do |format|
      if @asset_pair.save
        format.html do
          redirect_to asset_pair_url(@asset_pair),
                      notice: 'Asset pair was successfully created.'
        end
        format.json { render :show, status: :created, location: @asset_pair }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @asset_pair.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /asset_pairs/1 or /asset_pairs/1.json
  def update
    respond_to do |format|
      if @asset_pair.update(asset_pair_params)
        format.html do
          redirect_to asset_pair_url(@asset_pair),
                      notice: 'Asset pair was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @asset_pair }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @asset_pair.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /asset_pairs/1 or /asset_pairs/1.json
  def destroy
    @asset_pair.destroy

    respond_to do |format|
      format.html do
        redirect_to asset_pairs_url,
                    notice: 'Asset pair was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_asset_pair
    id = params[:id]
    return @asset_pair = asset_pairs.find(id) if id.match?(/\A[[:digit:]]+\z/)

    raise ActionController::RoutingError, "invalid id: #{id}"
  end

  # Only allow a list of trusted parameters through.
  def asset_pair_params
    params.require(:asset_pair).permit(:base_asset_id, :base_asset_type,
                                       :counter_asset_id, :counter_asset_type)
  end
end

app/helpers/asset_pairs_helper.rb
# frozen_string_literal: true

# :nodoc:
module AssetPairsHelper
end

app/views/asset_pairs/_asset_pair.html.erb
<div id="<%= dom_id asset_pair %>">
  <% if local_assigns[:show] %>
    <%= render asset_pair.base_asset, link: true %>

    <h3>
      <%= link_to asset_pair.counter_asset do %>
        <%= asset_pair.t(:counter_asset) %>:
        <%= asset_pair.counter_asset.to_human_s %>
      <% end %>
    </h3>

    <%= line_chart chart_data(asset_pair.exchange_rates) { |r| [r.observed_at, r.to_human_s ] } %>
  <% else %>
    <div>
      <%= link_to asset_pair.to_human_s, asset_pair %>
    </div>
    <% if asset_pair.exchange_rates.present? %>
      <div>
        <strong><%= asset_pair.exchange_rates.first.t(:exchange_rate)
                      %>:</strong>
        <span><%= asset_pair.exchange_rates.first.to_human_s %></span>
      </div>
      <div>
        <strong><%= asset_pair.exchange_rates.first.t(:observed_at) %>:</strong>
        <span><%= asset_pair.exchange_rates.first.observed_at %></span>
      </div>
    <% else %>
      <div>
        <i><%= ExchangeRate.t(:exchange_rate, count: 0) %></i>
      </div>
    <% end %>
  <% end %>
</div>

app/views/asset_pairs/_form.html.erb
<%= form_with(model: asset_pair) do |form| %>
  <% if asset_pair.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(asset_pair.errors.count, "error") %> prohibited this asset_pair from being saved:</h2>

      <ul>
        <% asset_pair.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :base_asset_id, style: "display: block" %>
    <%= form.text_field :base_asset_id %>
  </div>

  <div>
    <%= form.label :base_asset_type, style: "display: block" %>
    <%= form.text_field :base_asset_type %>
  </div>

  <div>
    <%= form.label :counter_asset_id, style: "display: block" %>
    <%= form.text_field :counter_asset_id %>
  </div>

  <div>
    <%= form.label :counter_asset_type, style: "display: block" %>
    <%= form.text_field :counter_asset_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/asset_pairs/edit.html.erb
<h1>Editing asset pair</h1>

<%= render "form", asset_pair: @asset_pair %>

<br>

<div>
  <%= link_to "Show this asset pair", @asset_pair %> |
  <%= link_to "Back to asset pairs", asset_pairs_path %>
</div>

app/views/asset_pairs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @asset_pairs.model_name.human %></h1>

<div id="asset_pairs">
  <% @asset_pairs.each do |asset_pair| %>
    <%= render asset_pair %>
  <% end %>
</div>

<%= link_to "New asset pair", new_asset_pair_path %>

app/views/asset_pairs/new.html.erb
<h1>New asset pair</h1>

<%= render "form", asset_pair: @asset_pair %>

<br>

<div>
  <%= link_to "Back to asset pairs", asset_pairs_path %>
</div>

app/views/asset_pairs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @asset_pair, show: true %>

<div>
  <%= link_to "Edit this asset pair", edit_asset_pair_path(@asset_pair) %> |
  <%= link_to "Back to asset pairs", asset_pairs_path %>

  <%= button_to "Destroy this asset pair", @asset_pair, method: :delete %>
</div>