config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'site#index'

  namespace :market_data, only: %i[index show] do
    resources :currencies, id: /[[:upper:]]{6}|[[:digit:]]+/
    resources :equities
    resources :options
  end

  resources :equities

  resources :asset_pairs do
    resources :exchange_rates, shallow: true
    resources :options, shallow: true do
      post 'compute', on: :member
    end
  end
  get 'options', to: 'options#index'

  # The Country and Currency models return the 3-letter alphabetic code instead
  # of their internal ID (except for historic currencies) in their #to_param
  # methods. We restrict the routing :id parameter to values that could be
  # internal ID, numeric code or alphabetic code.
  # We also restrict to the actions #index and #show.
  resources :currencies, id: /[[:upper:]]{3}|[[:digit:]]+/, only: %i[index show]
  resources :countries, id: /[[:upper:]]{2,3}|[[:digit:]]+/,
                        only: %i[index show] do
    resources :exchanges, id: /.*/, shallow: true
  end
  get '/exchanges', to: 'exchanges#index'

  # Redirect alphabetic codes that aren't written in, but required to be,
  # entirely uppercase to the uppercase equivalent.
  # Each line in the following Hash is of the format
  # +controller: id_constraints+
  {
    countries: /[[:alpha:]]{2,3}/,
    currencies: /[[:alpha:]]{3}/,
    'market_data/currencies': /[[:alpha:]]{6}/
  }.each do |controller, id|
    get "/#{controller}/:id",
        id:, to: redirect { |p| "/#{controller}/#{p[:id].upcase}" }
  end
end

app/models/asset_pair/equity.rb
# frozen_string_literal: true

##
# Class enabling the rendering of AssetPairs in a dedicated
# equity controller while maintaining the ability to manage
# AssetPairs regardless of type in the AssetPairsController.
class AssetPair::Equity < AssetPair
  class << self
    def preload_all(...) = super.preload(base_asset: :exchange)
  end
end

app/models/equity.rb
# frozen_string_literal: true

##
# Equity, typically company stock.
class Equity < ApplicationRecord
  include Asset

  has_one :security_listing, as: :security, dependent: :delete
  has_one :exchange, through: :security_listing

  validates :symbol, format: { without: /:/ }, presence: true
  validates :name, presence: true

  class << self
    ##
    # Returns the record corresponding to the given Equity and Exchange symbols,
    # +nil+ if not found.
    #
    # :call-seq: find_by_compound_symbol(exchange:, equity:) => ...
    def find_by_compound_symbol(**) = _find_by_compound_symbol(**).first

    ##
    # Like #find_by_compound_symbol, but raises an Error if no record can be
    # found.
    def find_by_compound_symbol!(**) = _find_by_compound_symbol(**).first!

    private

    def _find_by_compound_symbol(exchange: nil, equity: nil)
      with_exchange_symbol.where(symbol: equity)
                          .merge(Exchange.where(symbol: exchange))
    end
  end

  ##
  # Returns a relation that includes the symbol of the exchange the equities are
  # listed on.
  #
  # Selects all of Equity's columns, plus Exchange#symbol.
  scope :with_exchange, -> { includes(:exchange).references(:exchange) }
  singleton_class.__send__(:alias_method, :with_exchange_symbol, :with_exchange)

  ##
  # Returns +exchange.symbol+.
  def exchange_symbol = exchange&.symbol

  def to_asset_pair_params
    counter_asset_id = Currency.active
                               .joins(countries: { exchanges: :equities })
                               .merge(Equity.where(id:))
                               .reorder(:id).pick(:id) || Currency.XXX.id

    {
      asset_pair: {
        base_asset_id: id, base_asset_type: self.class,
        counter_asset_id:, counter_asset_type: 'Currency'
      }
    }
  end

  def to_param
    return super unless association(:exchange).loaded?

    [exchange_symbol, symbol].compact.join(':')
  end

  def to_human_s(*, **opts)
    default = association(:exchange).loaded? ? to_param : symbol

    super(*, **opts.merge(default:))
  end
end

app/controllers/equities_controller.rb
# frozen_string_literal: true

# :nodoc:
class EquitiesController < ApplicationController
  include self::Finders

  before_action :set_equity, only: %i[show edit update destroy]

  # GET /equities or /equities.json
  def index
    @equities = equities
  end

  # GET /equities/1 or /equities/1.json
  def show
    @asset_pairs = AssetPair.of(@equity)
  end

  # GET /equities/new
  def new
    @equity = Equity.new
  end

  # GET /equities/1/edit
  def edit; end

  # POST /equities or /equities.json
  def create
    @equity = Equity.new(equity_params)

    respond_to do |format|
      if @equity.save
        format.html do
          redirect_to equity_url(@equity),
                      notice: 'Equity was successfully created.'
        end
        format.json { render :show, status: :created, location: @equity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @equity.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /equities/1 or /equities/1.json
  def update
    respond_to do |format|
      if @equity.update(equity_params)
        format.html do
          redirect_to equity_url(@equity),
                      notice: 'Equity was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @equity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @equity.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /equities/1 or /equities/1.json
  def destroy
    @equity.destroy

    respond_to do |format|
      format.html do
        redirect_to equities_url, notice: 'Equity was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  ##
  # Initializes the `@equity` instance variable.
  #
  # All of the following routes will show the same equity:
  # * equities/1
  # * equities/Nasdaq:AAPL
  # * equities/Nasdaq:aapl
  # * equities/AAPL
  # * equities/aapl
  def set_equity
    @equity = find_equity_or_redirect(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def equity_params
    params.require(:equity).permit(:symbol, :name)
  end
end

app/controllers/market_data/equities_controller.rb
# frozen_string_literal: true

##
# Inherits from AssetPairsController to explicitly handle AssetPairs where
# #base_asset is of type Equity.
class MarketData::EquitiesController < AssetPairsController
  include ::EquitiesController::Finders

  private

  def set_asset_pair
    super
  rescue ActionController::RoutingError
    base_asset = find_equity_or_redirect(params[:id])

    # #find_equity_or_redirect only returns nil when a redirect was initiated,
    # hence skip querying the DB in this case.
    @asset_pair = asset_pairs.find_by!(base_asset:) if base_asset.present?
  end
end

app/helpers/equities_helper.rb
# frozen_string_literal: true

# :nodoc:
module EquitiesHelper
end

app/views/equities/_equity.html.erb
<div id="<%= dom_id equity %>">
  <%= content_tag local_assigns.fetch(:tag, :h2) do %>
    <% if local_assigns[:link] %>
      <%= link_to "#{equity.name} (#{equity.symbol})", equity %>
    <% else %>
      <%= equity.name %> (<%= equity.symbol %>)
    <% end %>
  <% end %>
</div>

app/views/equities/_form.html.erb
<%= form_with(model: equity) do |form| %>
  <% if equity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(equity.errors.count, "error") %> prohibited this equity from being saved:</h2>

      <ul>
        <% equity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :symbol, style: "display: block" %>
    <%= form.text_field :symbol %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/equities/edit.html.erb
<h1>Editing equity</h1>

<%= render "form", equity: @equity %>

<br>

<div>
  <%= link_to "Show this equity", @equity %> |
  <%= link_to "Back to equities", equities_path %>
</div>

app/views/equities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Equities</h1>

<div id="equities">
  <% @equities.each do |equity| %>
    <%= render equity %>
    <p>
      <%= link_to "Show this equity", equity %>
    </p>
  <% end %>
</div>

<%= link_to "New equity", new_equity_path %>

app/views/equities/new.html.erb
<h1>New equity</h1>

<%= render "form", equity: @equity %>

<br>

<div>
  <%= link_to "Back to equities", equities_path %>
</div>

app/views/equities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @equity %>

<div>
  <%= link_to "Edit this equity", edit_equity_path(@equity) %> |
  <%= link_to "Back to equities", equities_path %>

  <%= button_to "Destroy this equity", @equity, method: :delete %>
  <%= render 'shared/asset/create_asset_pair', asset: @equity %>
</div>