config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'site#index'

  namespace :market_data, only: %i[index show] do
    resources :currencies, id: /[[:upper:]]{6}|[[:digit:]]+/
    resources :equities
    resources :options
  end

  resources :equities

  resources :asset_pairs do
    resources :exchange_rates, shallow: true
    resources :options, shallow: true do
      post 'compute', on: :member
    end
  end
  get 'options', to: 'options#index'

  # The Country and Currency models return the 3-letter alphabetic code instead
  # of their internal ID (except for historic currencies) in their #to_param
  # methods. We restrict the routing :id parameter to values that could be
  # internal ID, numeric code or alphabetic code.
  # We also restrict to the actions #index and #show.
  resources :currencies, id: /[[:upper:]]{3}|[[:digit:]]+/, only: %i[index show]
  resources :countries, id: /[[:upper:]]{2,3}|[[:digit:]]+/,
                        only: %i[index show] do
    resources :exchanges, id: /.*/, shallow: true
  end
  get '/exchanges', to: 'exchanges#index'

  # Redirect alphabetic codes that aren't written in, but required to be,
  # entirely uppercase to the uppercase equivalent.
  # Each line in the following Hash is of the format
  # +controller: id_constraints+
  {
    countries: /[[:alpha:]]{2,3}/,
    currencies: /[[:alpha:]]{3}/,
    'market_data/currencies': /[[:alpha:]]{6}/
  }.each do |controller, id|
    get "/#{controller}/:id",
        id:, to: redirect { |p| "/#{controller}/#{p[:id].upcase}" }
  end
end

app/models/exchange_rate.rb
# frozen_string_literal: true

require 'sti_preload/exchange_rate'

##
# For most assets, this simply represents the value of the asset (#base_asset)
# in a currency (#counter_asset).
# The value is processed as Rational and stored as #counter_rate (numerator) and
# #base_rate (denominator) in the database.
class ExchangeRate < ApplicationRecord
  include StiPreload::ExchangeRate

  class << self
    def denominator_column_name(name)
      return 'base_rate' if name == 'exchange_rate'

      super
    end

    def numerator_column_name(name)
      return 'counter_rate' if name == 'exchange_rate'

      super
    end
  end

  belongs_to :asset_pair

  validates :base_rate, numericality: { only_integer: true, other_than: 0 }
  validates :counter_rate, numericality: { only_integer: true }
  validates :observed_at, presence: true

  # :section: Type selectors ################################################

  ##
  # Returns a relation where the records are of #type +type+.
  scope :of_type, ->(type) { where(type: type.to_s) }

  # :section: Time selectors ################################################

  ##
  # Returns a relation where the records were observed after the specified
  # +time+.
  scope :after, lambda { |time, strict: false|
                  where("observed_at #{strict ? '>' : '>='} ?", time)
                }

  ##
  # Returns a relation where the records were observed before the specified
  # +time+.
  scope :before, lambda { |time, strict: false|
    where("observed_at #{strict ? '<' : '<='} ?", time)
  }

  ##
  # Returns a relation where the records were observed during the given time
  # period.
  # :call-seq:
  #   ExchangeRate.during(range) => ...
  #   ExchangeRate.during(start_time, end_time) => ...
  scope :during,
        lambda { |range, time = nil|
          range = range...time if time.present?

          where(observed_at: range)
        }
  singleton_class.send(:alias_method, :between, :during)

  ##
  # Returns the record that was observed at the latest point in time, per
  # AssetPair.
  scope :latest, -> { group(:asset_pair_id).having('MAX(observed_at)') }

  ##
  # Like ::latest, but doesn't exclude records that don't have an associated
  # ExchangeRate already in more complex queries
  scope :latest_or_none, -> { latest.or(having('COUNT(observed_at) = 0')) }

  ##
  # Returns the records that were observed the closest to each of the specified
  # +times+, per AssetPair.
  scope :observed_near,
        lambda { |*times|
          # Map the times to their Unix timestamps and interpolate them into
          # constant rows of a "sampled_at" column.
          timetable = times.map(&:to_i).map! do |time|
            sanitize_sql(['SELECT ? AS sampled_at', time])
          end
          timetable = Arel.sql(timetable.join(' UNION '))

          select('*').joins("CROSS JOIN (#{timetable})")
                     .group(:asset_pair_id, :sampled_at)
                     .having('MIN(ABS(UNIXEPOCH(observed_at) - sampled_at))')
        }
  singleton_class.send(:alias_method, :at, :observed_near)

  # :section: Rate selectors ################################################

  ##
  # Returns a relation with records having the highest #exchange_rate per
  # #asset_pair.
  scope :high, -> { group(:asset_pair_id).having('MAX(exchange_rate)') }

  ##
  # Returns a relation with records having the lowest #exchange_rate per
  # #asset_pair.
  scope :low, -> { group(:asset_pair_id).having('MIN(exchange_rate)') }

  # :section: Attributes

  attribute :observed_at, default: -> { Time.zone.now }

  alias_attribute :exchange_value, :exchange_rate
  alias_attribute :fx_rate,        :exchange_rate
  alias_attribute :price,          :exchange_rate
  alias_attribute :rate,           :exchange_rate
  alias_attribute :value,          :exchange_rate

  # :section: Instance methods

  ##
  # Returns a new instance of this class with the exchange rate as if the
  # assets were reversed.
  def mirror
    attrs = attributes.reject { |key| key.in?(%w[id created_at updated_at]) }
    attrs[:base_rate], attrs[:counter_rate] =
      *attrs.values_at(:counter_rate, :base_rate)

    self.class.new(**attrs)
  end
end

app/models/exchange_rate/chart.rb
# frozen_string_literal: true

class ExchangeRate::Chart < ExchangeRate; end

app/models/exchange_rate/chart/adjusted_rate.rb
# frozen_string_literal: true

class ExchangeRate::Chart::AdjustedRate < ExchangeRate::Chart; end

app/models/exchange_rate/chart/other.rb
# frozen_string_literal: true

class ExchangeRate::Chart::Other < ExchangeRate::Chart; end

app/models/exchange_rate/chart/rate.rb
# frozen_string_literal: true

class ExchangeRate::Chart::Rate < ExchangeRate::Chart; end

app/models/exchange_rate/net_asset_value.rb
# frozen_string_literal: true

class ExchangeRate::NetAssetValue < ExchangeRate; end

app/models/exchange_rate/other.rb
# frozen_string_literal: true

class ExchangeRate::Other < ExchangeRate; end

app/models/exchange_rate/quote/ask.rb
# frozen_string_literal: true

class ExchangeRate::Quote::Ask < ExchangeRate; end

app/models/exchange_rate/quote/bid.rb
# frozen_string_literal: true

class ExchangeRate::Quote::Bid < ExchangeRate; end

app/models/exchange_rate/quote/mid.rb
# frozen_string_literal: true

class ExchangeRate::Quote::Mid < ExchangeRate; end

app/models/exchange_rate/settlement_rate.rb
# frozen_string_literal: true

class ExchangeRate::SettlementRate < ExchangeRate; end

app/models/exchange_rate/trade.rb
# frozen_string_literal: true

class ExchangeRate::Trade < ExchangeRate; end

app/controllers/exchange_rates_controller.rb
# frozen_string_literal: true

# :nodoc:
class ExchangeRatesController < ApplicationController
  before_action :set_asset_pair, only: %i[index show new destroy]
  before_action :set_exchange_rate, only: %i[show edit update destroy]

  # GET /exchange_rates or /exchange_rates.json
  def index
    @exchange_rates = ExchangeRate.where(asset_pair: @asset_pair)
  end

  # GET /exchange_rates/1 or /exchange_rates/1.json
  def show; end

  # GET /exchange_rates/new
  def new
    @exchange_rate = ExchangeRate.new(asset_pair: @asset_pair)
  end

  # GET /exchange_rates/1/edit
  def edit; end

  # POST /exchange_rates or /exchange_rates.json
  def create
    @exchange_rate = ExchangeRate.new(exchange_rate_params)

    respond_to do |format|
      if @exchange_rate.save
        format.html do
          redirect_to asset_pair_url(@exchange_rate.asset_pair,
                                     exchange_rate_id: @exchange_rate,
                                     exchange_rate_type: @exchange_rate.type),
                      notice: 'Exchange rate was successfully created.'
        end
        format.json { render :show, status: :created, location: @exchange_rate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @exchange_rate.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /exchange_rates/1 or /exchange_rates/1.json
  def update
    respond_to do |format|
      if @exchange_rate.update(exchange_rate_params)
        format.html do
          redirect_to asset_pair_url(@exchange_rate.asset_pair,
                                     highlight: @exchange_rate),
                      notice: 'Exchange rate was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @exchange_rate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @exchange_rate.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /exchange_rates/1 or /exchange_rates/1.json
  def destroy
    @exchange_rate.destroy

    respond_to do |format|
      format.html do
        redirect_to asset_pair_url(@asset_pair),
                    notice: 'Exchange rate was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exchange_rate
    @exchange_rate = ExchangeRate.find(params[:id])
  end

  def set_asset_pair
    @asset_pair = AssetPair.find(params[:asset_pair_id])
  end

  # Only allow a list of trusted parameters through.
  def exchange_rate_params
    params.require(:exchange_rate).permit(:asset_pair_id, :base_rate,
                                          :counter_rate, :observed_at)
  end
end

app/helpers/exchange_rates_helper.rb
# frozen_string_literal: true

# :nodoc:
module ExchangeRatesHelper
end

app/views/exchange_rates/_exchange_rate.html.erb
<div id="<%= dom_id exchange_rate %>">
  <p>
    <strong>Asset pair:</strong>
    <%= exchange_rate.asset_pair_id %>
  </p>

  <p>
    <strong>Base rate:</strong>
    <%= exchange_rate.base_rate %>
  </p>

  <p>
    <strong>Counter rate:</strong>
    <%= exchange_rate.counter_rate %>
  </p>

  <p>
    <strong>Observed at:</strong>
    <%= exchange_rate.observed_at %>
  </p>

</div>

app/views/exchange_rates/_form.html.erb
<%= form_with(model: exchange_rate) do |form| %>
  <% if exchange_rate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exchange_rate.errors.count, "error") %> prohibited this exchange_rate from being saved:</h2>

      <ul>
        <% exchange_rate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :asset_pair_id, style: "display: block" %>
    <%= form.text_field :asset_pair_id %>
  </div>

  <div>
    <%= form.label :base_rate, style: "display: block" %>
    <%= form.number_field :base_rate %>
  </div>

  <div>
    <%= form.label :counter_rate, style: "display: block" %>
    <%= form.number_field :counter_rate %>
  </div>

  <div>
    <%= form.label :observed_at, style: "display: block" %>
    <%= form.datetime_field :observed_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exchange_rates/edit.html.erb
<h1>Editing exchange rate</h1>

<%= render "form", exchange_rate: @exchange_rate %>

<br>

<div>
  <%= link_to "Show this exchange rate", @exchange_rate %> |
  <%= link_to "Back to exchange rates", exchange_rates_path %>
</div>

app/views/exchange_rates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Exchange rates</h1>

<div id="exchange_rates">
  <% @exchange_rates.each do |exchange_rate| %>
    <%= render exchange_rate %>
    <p>
      <%= link_to "Show this exchange rate", exchange_rate %>
    </p>
  <% end %>
</div>

<%= link_to "New exchange rate", new_exchange_rate_path %>

app/views/exchange_rates/new.html.erb
<h1>New exchange rate</h1>

<%= render "form", exchange_rate: @exchange_rate %>

<br>

<div>
  <%= link_to "Back to exchange rates", exchange_rates_path %>
</div>

app/views/exchange_rates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exchange_rate %>

<div>
  <%= link_to "Edit this exchange rate", edit_exchange_rate_path(@exchange_rate) %> |
  <%= link_to "Back to exchange rates", exchange_rates_path %>

  <%= button_to "Destroy this exchange rate", @exchange_rate, method: :delete %>
</div>